# Generated by Django 4.2.16 on 2026-05-01 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fix_auto_field_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('book_no', models.CharField(max_length=50, unique=True)),
                ('added_by', models.CharField(max_length=50)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lbas_book_records',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='record_number',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book', to='core.bookrecord'),
        ),
    ]
