# Generated by Django 4.2.16 on 2026-05-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_bookrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school_level', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.CharField(max_length=50)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lbas_courses',
                'unique_together': {('name', 'school_level')},
            },
        ),
    ]
