# Generated by Django 4.2.16 on 2026-05-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtpRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_id", models.CharField(db_index=True, max_length=50)),
                ("otp_hash", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("lockout_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "lbas_otp_requests",
            },
        ),
        migrations.CreateModel(
            name="ProblemReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_id", models.CharField(db_index=True, max_length=50)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="pending", max_length=20)),
            ],
            options={
                "db_table": "lbas_problem_reports",
            },
        ),
    ]
